Zona.create!([
  {codigo: "01", descripcion: "BUENOS AIRES", srid: 22185, provincia: "BUENOS AIRES", codigo_indec: "06"},
  {codigo: "02", descripcion: "CATAMARCA", srid: 22182, provincia: "CATAMARCA", codigo_indec: "10"},
  {codigo: "03", descripcion: "CORDOBA", srid: 22183, provincia: "CORDOBA", codigo_indec: "14"},
  {codigo: "04", descripcion: "CORRIENTES", srid: 22186, provincia: "CORRIENTES", codigo_indec: "18"},
  {codigo: "05", descripcion: "CHACO", srid: 22185, provincia: "CHACO", codigo_indec: "22"},
  {codigo: "06", descripcion: "CHUBUT", srid: 22181, provincia: "CHUBUT", codigo_indec: "26"},
  {codigo: "07", descripcion: "ENTRE RIOS", srid: 22185, provincia: "ENTRE RIOS", codigo_indec: "30"},
  {codigo: "08", descripcion: "FORMOSA", srid: 22185, provincia: "FORMOSA", codigo_indec: "34"},
  {codigo: "09", descripcion: "JUJUY", srid: 22183, provincia: "JUJUY", codigo_indec: "38"},
  {codigo: "10", descripcion: "LA PAMPA", srid: 22182, provincia: "LA PAMPA", codigo_indec: "42"},
  {codigo: "11", descripcion: "LA RIOJA", srid: 22182, provincia: "LA RIOJA", codigo_indec: "46"},
  {codigo: "12", descripcion: "MENDOZA", srid: 22182, provincia: "MENDOZA", codigo_indec: "50"},
  {codigo: "13", descripcion: "MISIONES", srid: 22187, provincia: "MISIONES", codigo_indec: "54"},
  {codigo: "14", descripcion: "NEUQUEN", srid: 22181, provincia: "NEUQUEN", codigo_indec: "58"},
  {codigo: "15", descripcion: "RIO NEGRO", srid: 22181, provincia: "RIO NEGRO", codigo_indec: "62"},
  {codigo: "16", descripcion: "SALTA", srid: 22183, provincia: "SALTA", codigo_indec: "66"},
  {codigo: "17", descripcion: "SAN JUAN", srid: 22182, provincia: "SAN JUAN", codigo_indec: "70"},
  {codigo: "18", descripcion: "SAN LUIS", srid: 22183, provincia: "SAN LUIS", codigo_indec: "74"},
  {codigo: "19", descripcion: "SANTA CRUZ", srid: 22181, provincia: "SANTA CRUZ", codigo_indec: "78"},
  {codigo: "20", descripcion: "SANTA FE", srid: 22185, provincia: "SANTA FE", codigo_indec: "82"},
  {codigo: "21", descripcion: "SANTIAGO DEL ESTERO", srid: 22183, provincia: "SANTIAGO DEL ESTERO", codigo_indec: "86"},
  {codigo: "22", descripcion: "TIERRA DEL FUEGO", srid: 22182, provincia: "TIERRA DEL FUEGO", codigo_indec: "94"},
  {codigo: "23", descripcion: "TUCUMAN", srid: 22183, provincia: "TUCUMAN", codigo_indec: "90"},
  {codigo: "24", descripcion: "DELTA BONAERENSE", srid: 22185, provincia: "BUENOS AIRES", codigo_indec: "06"},
  {codigo: "25", descripcion: "DELTA ENTRERIANO", srid: 22185, provincia: "ENTRE RIOS", codigo_indec: "30"},
  {codigo: "26", descripcion: "CAPITAL FEDERAL", srid: 22185, provincia: "CAPITAL FEDERAL", codigo_indec: "02"}
])
