Especie.create!([
  {codigo_sp: "ACAE", codigo: "AE", genero_id: 1, nombre_cientifico: "Acacia mearnsii", nombre_comun: "Acacia del centenario", inscripcion_inase: ""},
  {codigo_sp: "ACAL", codigo: "AL", genero_id: 1, nombre_cientifico: "Acacia longifolia", nombre_comun: "Acacia trinervis", inscripcion_inase: ""},
  {codigo_sp: "ACAM", codigo: "AM", genero_id: 1, nombre_cientifico: "Acacia melanoxylon", nombre_comun: "Acacia australiana", inscripcion_inase: ""},
  {codigo_sp: "ACNA", codigo: "NA", genero_id: 1, nombre_cientifico: "Acacia sp.", nombre_comun: "Acacia", inscripcion_inase: ""},
  {codigo_sp: "AENA", codigo: "NA", genero_id: 2, nombre_cientifico: "Arce spp.", nombre_comun: "Arce", inscripcion_inase: ""},
  {codigo_sp: "AIAT", codigo: "AT", genero_id: 3, nombre_cientifico: "Ailanthus altisima", nombre_comun: "Árbol del cielo", inscripcion_inase: ""},
  {codigo_sp: "ALAG", codigo: "AG", genero_id: 4, nombre_cientifico: "Alnus glutinosa", nombre_comun: "Aliso europeo", inscripcion_inase: ""},
  {codigo_sp: "ANAM", codigo: "AM", genero_id: 5, nombre_cientifico: "Anadenanthera macrocarpa", nombre_comun: "Cebil Rojo", inscripcion_inase: ""},
  {codigo_sp: "ARAA", codigo: "AA", genero_id: 7, nombre_cientifico: "Araucaria angustifolia", nombre_comun: "Pino paraná", inscripcion_inase: ""},
  {codigo_sp: "ARAB", codigo: "AB", genero_id: 7, nombre_cientifico: "Araucaria bidwillii", nombre_comun: "Araucaria bidwilli o pino bunya", inscripcion_inase: ""},
  {codigo_sp: "ARAH", codigo: "AH", genero_id: 7, nombre_cientifico: "Araucaria heterophylla", nombre_comun: "Araucaria excelsa", inscripcion_inase: ""},
  {codigo_sp: "AUAC", codigo: "AC", genero_id: 10, nombre_cientifico: "Austrocedrus chilensis", nombre_comun: "Ciprés de la cordillera", inscripcion_inase: "MB"},
  {codigo_sp: "BABR", codigo: "BR", genero_id: 11, nombre_cientifico: "Balfourodendron riedelianum", nombre_comun: "Guatambú", inscripcion_inase: ""},
  {codigo_sp: "BSBD", codigo: "BD", genero_id: 12, nombre_cientifico: "Bastardiopsis densiflora", nombre_comun: "Loro blanco", inscripcion_inase: ""},
  {codigo_sp: "CACC", codigo: "CC", genero_id: 13, nombre_cientifico: "Casuarina cunninghamiana", nombre_comun: "Casuarina", inscripcion_inase: ""},
  {codigo_sp: "CDCD", codigo: "CD", genero_id: 14, nombre_cientifico: "Cedrus deodara", nombre_comun: "Cedro", inscripcion_inase: ""},
  {codigo_sp: "CECA", codigo: "CA", genero_id: 15, nombre_cientifico: "Cedrela angustifolia (C. balansae)", nombre_comun: "Cedro rosado o cedro salteño", inscripcion_inase: ""},
  {codigo_sp: "CECF", codigo: "CF", genero_id: 15, nombre_cientifico: "Cedrela fissilis", nombre_comun: "Cedro misionero", inscripcion_inase: ""},
  {codigo_sp: "CECL", codigo: "CL", genero_id: 15, nombre_cientifico: "Cedrela lilloi", nombre_comun: "Cedro salteño o cedro peludo", inscripcion_inase: ""},
  {codigo_sp: "CECT", codigo: "CT", genero_id: 15, nombre_cientifico: "Cedrela tubiflora var. macrocarpa", nombre_comun: "Cedro colorado o cedro misionero", inscripcion_inase: ""},
  {codigo_sp: "CENA", codigo: "NA", genero_id: 15, nombre_cientifico: "Cedrela sp.", nombre_comun: "Cedro", inscripcion_inase: ""},
  {codigo_sp: "CLCU", codigo: "CU", genero_id: 16, nombre_cientifico: "Celtis australis", nombre_comun: "Almez", inscripcion_inase: ""},
  {codigo_sp: "CNCN", codigo: "CN", genero_id: 17, nombre_cientifico: "Cunninghamia lanceolata", nombre_comun: "Cuningamia", inscripcion_inase: ""},
  {codigo_sp: "COCT", codigo: "CT", genero_id: 18, nombre_cientifico: "Cordia trichotoma", nombre_comun: "Peteribí", inscripcion_inase: ""},
  {codigo_sp: "CYCI", codigo: "CI", genero_id: 22, nombre_cientifico: "Carya illinoinensis", nombre_comun: "Nuez Pecán", inscripcion_inase: ""},
  {codigo_sp: "CSCV", codigo: "CV", genero_id: 20, nombre_cientifico: "Castanea sativa", nombre_comun: "Castaño", inscripcion_inase: ""},
  {codigo_sp: "CUCM", codigo: "CM", genero_id: 21, nombre_cientifico: "Cupressus macrocarpa", nombre_comun: "Ciprés lambertiana", inscripcion_inase: ""},
  {codigo_sp: "CUCS", codigo: "CS", genero_id: 21, nombre_cientifico: "Cupressus sempervirens", nombre_comun: "Ciprés común", inscripcion_inase: ""},
  {codigo_sp: "ENCO", codigo: "CO", genero_id: 23, nombre_cientifico: "Enterolobium contortisiliquum", nombre_comun: "Pacará, Timbó, Oreja de Negro", inscripcion_inase: ""},
  {codigo_sp: "EUEC", codigo: "EC", genero_id: 24, nombre_cientifico: "Eucalyptus camaldulensis", nombre_comun: "Eucalipto rostrata", inscripcion_inase: "MB"},
  {codigo_sp: "EUED", codigo: "ED", genero_id: 24, nombre_cientifico: "Eucalyptus dunnii", nombre_comun: "Eucalipto duni", inscripcion_inase: "MB"},
  {codigo_sp: "EUEG", codigo: "EG", genero_id: 24, nombre_cientifico: "Eucalyptus grandis", nombre_comun: "Eucalipto grandis", inscripcion_inase: "MB"},
  {codigo_sp: "EUEG01", codigo: "EG", genero_id: 24, nombre_cientifico: "Eucalyptus grandis cv. \"EG-INTA-1\"", nombre_comun: "Eucalipto EG-INTA-1", inscripcion_inase: "RNC - MB"},
  {codigo_sp: "EUEG02", codigo: "EG", genero_id: 24, nombre_cientifico: "Eucalyptus grandis cv. \"EG-INTA-152\"", nombre_comun: "Eucalipto EG-INTA-152", inscripcion_inase: "RNC - MB"},
  {codigo_sp: "EUEG03", codigo: "EG", genero_id: 24, nombre_cientifico: "Eucalyptus grandis cv. \"EG-INTA-155\"", nombre_comun: "Eucalipto EG-INTA-155", inscripcion_inase: "RNC - MB"},
  {codigo_sp: "EUEG04", codigo: "EG", genero_id: 24, nombre_cientifico: "Eucalyptus grandis cv. \"EG-INTA-157\"", nombre_comun: "Eucalipto EG-INTA-157", inscripcion_inase: "RNC - MB"},
  {codigo_sp: "EUEG05", codigo: "EG", genero_id: 24, nombre_cientifico: "Eucalyptus grandis cv. \"EG-INTA-164\"", nombre_comun: "Eucalipto EG-INTA-164", inscripcion_inase: "RNC - MB"},
  {codigo_sp: "EUEG06", codigo: "EG", genero_id: 24, nombre_cientifico: "Eucalyptus grandis cv. \"EG-INTA-2\"", nombre_comun: "Eucalipto EG-INTA-2", inscripcion_inase: "RNC - MB"},
  {codigo_sp: "EUEG07", codigo: "EG", genero_id: 24, nombre_cientifico: "Eucalyptus grandis cv. \"EG-INTA-22\"", nombre_comun: "Eucalipto EG-INTA-22", inscripcion_inase: "RNC - MB"},
  {codigo_sp: "EUEG08", codigo: "EG", genero_id: 24, nombre_cientifico: "Eucalyptus grandis cv. \"EG-INTA-24\"", nombre_comun: "Eucalipto EG-INTA-24", inscripcion_inase: "RNC - MB"},
  {codigo_sp: "EUEG09", codigo: "EG", genero_id: 24, nombre_cientifico: "Eucalyptus grandis cv. \"EG-INTA-35\"", nombre_comun: "Eucalipto EG-INTA-35", inscripcion_inase: "RNC - MB"},
  {codigo_sp: "EUEG10", codigo: "EG", genero_id: 24, nombre_cientifico: "Eucalyptus grandis cv. \"EG-INTA-36\"", nombre_comun: "Eucalipto EG-INTA-36", inscripcion_inase: "RNC - MB"},
  {codigo_sp: "EUEG11", codigo: "EG", genero_id: 24, nombre_cientifico: "Eucalyptus grandis cv. \"FTSA A100-95\"", nombre_comun: "Eucalipto FTSA A100-95", inscripcion_inase: "RNC - MB"},
  {codigo_sp: "EUEG12", codigo: "EG", genero_id: 24, nombre_cientifico: "Eucalyptus grandis cv. \"FTSA A126-96\"", nombre_comun: "Eucalipto FTSA A126-96", inscripcion_inase: "RNC - MB"},
  {codigo_sp: "EUEG13", codigo: "EG", genero_id: 24, nombre_cientifico: "Eucalyptus grandis cv. \"FTSA A129-96\"", nombre_comun: "Eucalipto FTSA A129-96", inscripcion_inase: "RNC - MB"},
  {codigo_sp: "EUEG14", codigo: "EG", genero_id: 24, nombre_cientifico: "Eucalyptus grandis cv. \"FTSA A130-96\"", nombre_comun: "Eucalipto FTSA A130-96", inscripcion_inase: "RNC - MB"},
  {codigo_sp: "EUEG15", codigo: "EG", genero_id: 24, nombre_cientifico: "Eucalyptus grandis cv. \"GXU102\"", nombre_comun: "Eucalipto GXU102", inscripcion_inase: "RNC"},
  {codigo_sp: "EUEG16", codigo: "EG", genero_id: 24, nombre_cientifico: "Eucalyptus grandis cv. \"K.5128\"", nombre_comun: "Eucalipto K.5128", inscripcion_inase: "RNC"},
  {codigo_sp: "EUEG17", codigo: "EG", genero_id: 24, nombre_cientifico: "Eucalyptus grandis cv. \"K.5204\"", nombre_comun: "Eucalipto K.5204", inscripcion_inase: "RNC"},
  {codigo_sp: "EUEI", codigo: "EI", genero_id: 24, nombre_cientifico: "Eucalyptus citriodora", nombre_comun: "Eucalipto citriodora", inscripcion_inase: ""},
  {codigo_sp: "EUEL", codigo: "EL", genero_id: 24, nombre_cientifico: "Eucalyptus globulus", nombre_comun: "Eucalipto globulus", inscripcion_inase: ""},
  {codigo_sp: "EUELEL", codigo: "EL", genero_id: 24, nombre_cientifico: "Eucalyptus globulus ssp. globulus", nombre_comun: "Eucalipto blanco", inscripcion_inase: "MB"},
  {codigo_sp: "EUEM", codigo: "EM", genero_id: 24, nombre_cientifico: "Eucalyptus maidenii", nombre_comun: "Eucalipto maideni", inscripcion_inase: ""},
  {codigo_sp: "EUEO", codigo: "EO", genero_id: 24, nombre_cientifico: "Eucalyptus cloeziana", nombre_comun: "Eucalipto cloeziana", inscripcion_inase: "MB"},
  {codigo_sp: "EUES", codigo: "ES", genero_id: 24, nombre_cientifico: "Eucalyptus saligna", nombre_comun: "Eucalipto saligna", inscripcion_inase: ""},
  {codigo_sp: "EUET", codigo: "ET", genero_id: 24, nombre_cientifico: "Eucalyptus tereticornis", nombre_comun: "Eucalipto tereticornis", inscripcion_inase: ""},
  {codigo_sp: "EUEU", codigo: "EU", genero_id: 24, nombre_cientifico: "Eucalyptus urophylla", nombre_comun: "Eucalipto urophylla", inscripcion_inase: ""},
  {codigo_sp: "EUEV", codigo: "EV", genero_id: 24, nombre_cientifico: "Eucalyptus viminalis", nombre_comun: "Eucalipto viminalis", inscripcion_inase: "MB"},
  {codigo_sp: "EUEX", codigo: "EX", genero_id: 24, nombre_cientifico: "Eucalyptus sideroxylon", nombre_comun: "Eucalipto sideroxylon", inscripcion_inase: ""},
  {codigo_sp: "EUNA", codigo: "NA", genero_id: 24, nombre_cientifico: "Eucalyptus sp.", nombre_comun: "Eucalipto", inscripcion_inase: ""},
  {codigo_sp: "FRFA", codigo: "FA", genero_id: 25, nombre_cientifico: "Fraxinus americana", nombre_comun: "Fresno americano", inscripcion_inase: ""},
  {codigo_sp: "FRFE", codigo: "FE", genero_id: 25, nombre_cientifico: "Fraxinus excelsior", nombre_comun: "Fresno europeo", inscripcion_inase: ""},
  {codigo_sp: "FRNA", codigo: "NA", genero_id: 25, nombre_cientifico: "Fraxinus sp.", nombre_comun: "Fresno", inscripcion_inase: ""},
  {codigo_sp: "GLGT", codigo: "GT", genero_id: 26, nombre_cientifico: "Gleditsia triacanthos", nombre_comun: "Acacia negra", inscripcion_inase: ""},
  {codigo_sp: "GRGR", codigo: "GR", genero_id: 27, nombre_cientifico: "Grevillea robusta", nombre_comun: "Grevillea o roble sedoso", inscripcion_inase: "MB"},
  {codigo_sp: "HOHD", codigo: "HD", genero_id: 28, nombre_cientifico: "Hovenia dulcis", nombre_comun: "Palito Dulce", inscripcion_inase: ""},
  {codigo_sp: "JAMI", codigo: "MI", genero_id: 29, nombre_cientifico: "Jacaranda micrantha", nombre_comun: "Caroba", inscripcion_inase: ""},
  {codigo_sp: "JUJN", codigo: "JN", genero_id: 30, nombre_cientifico: "Juglans nigra", nombre_comun: "Nogal negro", inscripcion_inase: ""},
  {codigo_sp: "JUJR", codigo: "JR", genero_id: 30, nombre_cientifico: "Juglans regia", nombre_comun: "Nogal europeo", inscripcion_inase: ""},
  {codigo_sp: "LALD", codigo: "LD", genero_id: 31, nombre_cientifico: "Larix decidua", nombre_comun: "Alerce europeo", inscripcion_inase: ""},
  {codigo_sp: "LILL", codigo: "LL", genero_id: 32, nombre_cientifico: "Ligustrum lucidum", nombre_comun: "Ligustro", inscripcion_inase: ""},
  {codigo_sp: "LQLS", codigo: "LS", genero_id: 33, nombre_cientifico: "Liquidambar styraciflua", nombre_comun: "Liquidambar", inscripcion_inase: ""},
  {codigo_sp: "LULN", codigo: "LN", genero_id: 34, nombre_cientifico: "Laurus nobilis", nombre_comun: "Laurel", inscripcion_inase: ""},
  {codigo_sp: "MAMP", codigo: "MP", genero_id: 35, nombre_cientifico: "Maclura pomifera", nombre_comun: "Maclura", inscripcion_inase: ""},
  {codigo_sp: "MEMA", codigo: "MA", genero_id: 36, nombre_cientifico: "Melia azedarach", nombre_comun: "Paraíso", inscripcion_inase: ""},
  {codigo_sp: "MEMAMG", codigo: "MA", genero_id: 36, nombre_cientifico: "Melia azedarach var. gigantea", nombre_comun: "Paraíso gigante", inscripcion_inase: "MB"},
  {codigo_sp: "MOML", codigo: "ML", genero_id: 37, nombre_cientifico: "Morus alba", nombre_comun: "Morera blanca", inscripcion_inase: ""},
  {codigo_sp: "MYMF", codigo: "MF", genero_id: 39, nombre_cientifico: "Myrocarpus frondosus", nombre_comun: "Incienso", inscripcion_inase: ""},
  {codigo_sp: "NA", codigo: "", genero_id: nil, nombre_cientifico: "No disponible", nombre_comun: "", inscripcion_inase: ""},
  {codigo_sp: "NONN", codigo: "NN", genero_id: 40, nombre_cientifico: "Nothofagus nervosa", nombre_comun: "Raulí", inscripcion_inase: "MB"},
  {codigo_sp: "NONO", codigo: "NO", genero_id: 40, nombre_cientifico: "Nothofagus obliqua", nombre_comun: "Roble pellín", inscripcion_inase: "MB"},
  {codigo_sp: "NONP", codigo: "NP", genero_id: 40, nombre_cientifico: "Nothofagus pumilio", nombre_comun: "Lenga", inscripcion_inase: ""},
  {codigo_sp: "PAPW", codigo: "PW", genero_id: 41, nombre_cientifico: "Paulownia tomentosa", nombre_comun: "Kiri", inscripcion_inase: ""},
  {codigo_sp: "PDPR", codigo: "PR", genero_id: 43, nombre_cientifico: "Parapiptadenia rigida", nombre_comun: "Anchico", inscripcion_inase: ""},
  {codigo_sp: "PEPD", codigo: "PD", genero_id: 44, nombre_cientifico: "Peltophorum dubium", nombre_comun: "Caña Fístola", inscripcion_inase: ""},
  {codigo_sp: "PIHB", codigo: "HB", genero_id: 47, nombre_cientifico: "Pinus sp.", nombre_comun: "Pino híbrido", inscripcion_inase: ""},
  {codigo_sp: "PINA", codigo: "NA", genero_id: 47, nombre_cientifico: "Pinus sp.", nombre_comun: "Pino sp.", inscripcion_inase: ""},
  {codigo_sp: "PIPA", codigo: "PA", genero_id: 47, nombre_cientifico: "Pinus pinaster", nombre_comun: "Pino marítimo", inscripcion_inase: "MB"},
  {codigo_sp: "PIPB", codigo: "PB", genero_id: 47, nombre_cientifico: "Pinus brutia", nombre_comun: "Pino turco", inscripcion_inase: "MB"},
  {codigo_sp: "PIPC", codigo: "PC", genero_id: 47, nombre_cientifico: "Pinus caribaea", nombre_comun: "Pino caribaea", inscripcion_inase: ""},
  {codigo_sp: "PIPCPC", codigo: "PC", genero_id: 47, nombre_cientifico: "Pinus caribaea var. caribaea", nombre_comun: "Pino caribaea", inscripcion_inase: "MB"},
  {codigo_sp: "PIPCPD", codigo: "PC", genero_id: 47, nombre_cientifico: "Pinus caribaea var. hondurensis", nombre_comun: "Pino caribaea de Honduras", inscripcion_inase: ""},
  {codigo_sp: "PIPE", codigo: "PE", genero_id: 47, nombre_cientifico: "Pinus elliottii", nombre_comun: "Pino elioti", inscripcion_inase: ""},
  {codigo_sp: "PIPEPC", codigo: "PE", genero_id: 47, nombre_cientifico: "Pino híbrido filial 2", nombre_comun: "Pino taeda F2 (P. elliotti x P. caribaea)", inscripcion_inase: ""},
  {codigo_sp: "PIPEPD", codigo: "PE", genero_id: 47, nombre_cientifico: "Pinus elliottii x hondurensis", nombre_comun: "Pino híbrido", inscripcion_inase: ""},
  {codigo_sp: "PIPEPE", codigo: "PE", genero_id: 47, nombre_cientifico: "Pinus elliottii var. elliottii", nombre_comun: "Pino elioti", inscripcion_inase: "MB"},
  {codigo_sp: "PIPEPH", codigo: "PE", genero_id: 47, nombre_cientifico: "Pinus elliottii var. elliottii x Pinus caribaea var. hondurensis", nombre_comun: "Pino híbrido", inscripcion_inase: "MB"},
  {codigo_sp: "PIPF", codigo: "PF", genero_id: 47, nombre_cientifico: "Pinus canariensis", nombre_comun: "Pino canario", inscripcion_inase: "MB"},
  {codigo_sp: "PIPH", codigo: "PH", genero_id: 47, nombre_cientifico: "Pinus halepensis", nombre_comun: "Pino de Alepo", inscripcion_inase: ""},
  {codigo_sp: "PIPI", codigo: "PI", genero_id: 47, nombre_cientifico: "Pinus pinea", nombre_comun: "Pino piñonero", inscripcion_inase: ""},
  {codigo_sp: "PIPJ", codigo: "PJ", genero_id: 47, nombre_cientifico: "Pinus jeffreyi", nombre_comun: "Pino jeffreyi o pino jefri", inscripcion_inase: ""},
  {codigo_sp: "PIPM", codigo: "PM", genero_id: 47, nombre_cientifico: "Pinus monticola", nombre_comun: "Pino blanco occidental", inscripcion_inase: "MB"},
  {codigo_sp: "PIPN", codigo: "PN", genero_id: 47, nombre_cientifico: "Pinus nigra", nombre_comun: "Pino nigra", inscripcion_inase: ""},
  {codigo_sp: "PIPO", codigo: "PO", genero_id: 47, nombre_cientifico: "Pinus contorta", nombre_comun: "Pino contorta", inscripcion_inase: "MB"},
  {codigo_sp: "PIPOPL", codigo: "PO", genero_id: 47, nombre_cientifico: "Pinus contorta var. latifolia", nombre_comun: "Pino murrayana", inscripcion_inase: ""},
  {codigo_sp: "PIPOPM", codigo: "PO", genero_id: 47, nombre_cientifico: "Pinus contorta var. Murrayana", nombre_comun: "Pino murrayana", inscripcion_inase: "MB"},
  {codigo_sp: "PIPP", codigo: "PP", genero_id: 47, nombre_cientifico: "Pinus ponderosa", nombre_comun: "Pino ponderosa", inscripcion_inase: "MB"},
  {codigo_sp: "PIPPPP", codigo: "PP", genero_id: 47, nombre_cientifico: "Pinus ponderosa var. ponderosa", nombre_comun: "Pino ponderosa", inscripcion_inase: "MB"},
  {codigo_sp: "PIPR", codigo: "PR", genero_id: 47, nombre_cientifico: "Pinus radiata", nombre_comun: "Pino radiata o insigne", inscripcion_inase: "MB"},
  {codigo_sp: "PIPS", codigo: "PS", genero_id: 47, nombre_cientifico: "Pinus strobus", nombre_comun: "Pino blanco", inscripcion_inase: ""},
  {codigo_sp: "PIPT", codigo: "PT", genero_id: 47, nombre_cientifico: "Pinus taeda", nombre_comun: "Pino taeda", inscripcion_inase: "MB"},
  {codigo_sp: "PIPTHB", codigo: "PT", genero_id: 47, nombre_cientifico: "Pinus taeda híbrido", nombre_comun: "Pino taeda híbrido", inscripcion_inase: ""},
  {codigo_sp: "PIPTLI", codigo: "PT", genero_id: 47, nombre_cientifico: "Pinus taeda Livingston", nombre_comun: "Pino taeda livingston", inscripcion_inase: "MB"},
  {codigo_sp: "PIPTMA", codigo: "PT", genero_id: 47, nombre_cientifico: "Pinus taeda Marion", nombre_comun: "Pino taeda marion", inscripcion_inase: "MB"},
  {codigo_sp: "PIPU", codigo: "PU", genero_id: 47, nombre_cientifico: "Pinus patula", nombre_comun: "Pino patula", inscripcion_inase: ""},
  {codigo_sp: "PIPY", codigo: "PY", genero_id: 47, nombre_cientifico: "Pinus sylvestris", nombre_comun: "Pino escocés", inscripcion_inase: ""},
  {codigo_sp: "PIPZ", codigo: "PZ", genero_id: 47, nombre_cientifico: "Pinus tecunumanii", nombre_comun: "Pinabete", inscripcion_inase: ""},
  {codigo_sp: "PLPF", codigo: "PF", genero_id: 48, nombre_cientifico: "Platanus acerifolia", nombre_comun: "Plátano", inscripcion_inase: ""},
  {codigo_sp: "PONA", codigo: "NA", genero_id: 49, nombre_cientifico: "Populus sp.", nombre_comun: "Álamo", inscripcion_inase: ""},
  {codigo_sp: "POPA", codigo: "PA", genero_id: 49, nombre_cientifico: "Populus alba", nombre_comun: "Álamo plateado", inscripcion_inase: ""},
  {codigo_sp: "POPCGU", codigo: "PC", genero_id: 49, nombre_cientifico: "Populus x euroamericana cv. \"Guardi\"", nombre_comun: "Álamo Guardi", inscripcion_inase: "Trámite RNC"},
  {codigo_sp: "POPCPC", codigo: "PC", genero_id: 49, nombre_cientifico: "Populus x euroamericana cv. \"Conti\"", nombre_comun: "Álamo conti 12", inscripcion_inase: "Trámite RNC"},
  {codigo_sp: "POPCPH", codigo: "PC", genero_id: 49, nombre_cientifico: "Populus x euroamericana cv. \"I-214\"", nombre_comun: "Álamo I-214 o 214", inscripcion_inase: "Trámite RNC"},
  {codigo_sp: "POPCPI", codigo: "PC", genero_id: 49, nombre_cientifico: "Populus x euroamericana", nombre_comun: "Álamo Mussolini", inscripcion_inase: ""},
  {codigo_sp: "POPD", codigo: "PD", genero_id: 49, nombre_cientifico: "Populus deltoides", nombre_comun: "Álamo carolino", inscripcion_inase: ""},
  {codigo_sp: "POPD02", codigo: "PD", genero_id: 49, nombre_cientifico: "Populus deltoides cv. \"Australiano 106/60\"", nombre_comun: "Álamo Australiano 106/60", inscripcion_inase: "RNC - MB"},
  {codigo_sp: "POPD03", codigo: "PD", genero_id: 49, nombre_cientifico: "Populus deltoides cv. \"Carabelas INTA\"", nombre_comun: "Álamo carabelas", inscripcion_inase: "RNC - MB"},
  {codigo_sp: "POPDPA", codigo: "PD", genero_id: 49, nombre_cientifico: "Populus deltoides cv. \"Australiano 129/60\"", nombre_comun: "Álamo Australiano 129/60", inscripcion_inase: "RNC - MB"},
  {codigo_sp: "POPDPB", codigo: "PD", genero_id: 49, nombre_cientifico: "Populus deltoides cv. \"I-72\"", nombre_comun: "Álamo I-72", inscripcion_inase: ""},
  {codigo_sp: "POPDPC", codigo: "PD", genero_id: 49, nombre_cientifico: "Populus deltoides cv. \"Catfish 2\"", nombre_comun: "Álamo Catfish 2", inscripcion_inase: "Trámite RNC"},
  {codigo_sp: "POPDPD", codigo: "PD", genero_id: 49, nombre_cientifico: "Populus deltoides cv. \"Stoneville 67\"", nombre_comun: "Álamo stoneville", inscripcion_inase: "RNC - MB"},
  {codigo_sp: "POPDPH", codigo: "PD", genero_id: 49, nombre_cientifico: "Populus deltoides cv. “Harvard”  (I-63/51)", nombre_comun: "Álamo Harvard", inscripcion_inase: "Trámite RNC"},
  {codigo_sp: "POPE", codigo: "PE", genero_id: 49, nombre_cientifico: "Populus x canescens", nombre_comun: "Álamo cano o híbrido español", inscripcion_inase: ""},
  {codigo_sp: "POPF01", codigo: "PF", genero_id: 49, nombre_cientifico: "Populus x canadensis cv. \"Ragonese 22 INTA\"", nombre_comun: "Álamo Ragonese 22 INTA", inscripcion_inase: "RNC - MB"},
  {codigo_sp: "POPN", codigo: "PN", genero_id: 49, nombre_cientifico: "Populus nigra", nombre_comun: "Álamo negro", inscripcion_inase: ""},
  {codigo_sp: "POPNPI", codigo: "PN", genero_id: 49, nombre_cientifico: "Populus nigra cv. \"Italica\"", nombre_comun: "Álamo criollo", inscripcion_inase: ""},
  {codigo_sp: "POPT", codigo: "PT", genero_id: 49, nombre_cientifico: "Populus trichocarpa", nombre_comun: "Álamo trichocarpa", inscripcion_inase: ""},
  {codigo_sp: "PPNA", codigo: "NA", genero_id: 50, nombre_cientifico: "Prosopis sp.", nombre_comun: "Algarrobo", inscripcion_inase: "MB"},
  {codigo_sp: "PPPA", codigo: "PA", genero_id: 50, nombre_cientifico: "Prosopis alba", nombre_comun: "Algarrobo blanco", inscripcion_inase: "MB"},
  {codigo_sp: "PPPC", codigo: "PC", genero_id: 50, nombre_cientifico: "Prosopis chilensis", nombre_comun: "Algarrobo chileno", inscripcion_inase: ""},
  {codigo_sp: "PPPF", codigo: "PF", genero_id: 50, nombre_cientifico: "Prosopis flexuosa", nombre_comun: "Algarrobo negro o dulce", inscripcion_inase: ""},
  {codigo_sp: "PPPH", codigo: "PH", genero_id: 50, nombre_cientifico: "Prosopis hassleri", nombre_comun: "Algarrobo paraguayo", inscripcion_inase: ""},
  {codigo_sp: "PPPL", codigo: "PL", genero_id: 50, nombre_cientifico: "Prosopis caldenia", nombre_comun: "Caldén", inscripcion_inase: ""},
  {codigo_sp: "PPPN", codigo: "PN", genero_id: 50, nombre_cientifico: "Prosopis nigra", nombre_comun: "Algarrobo negro", inscripcion_inase: ""},
  {codigo_sp: "PRNA", codigo: "NA", genero_id: 51, nombre_cientifico: "Prunus sp.", nombre_comun: "Ciruelo y cerezo forestales", inscripcion_inase: ""},
  {codigo_sp: "PSPM", codigo: "PM", genero_id: 52, nombre_cientifico: "Pseudotsuga menziesii", nombre_comun: "Pino oregon", inscripcion_inase: "MB"},
  {codigo_sp: "PTPA", codigo: "PA", genero_id: 53, nombre_cientifico: "Patagonula americana", nombre_comun: "Guayubira", inscripcion_inase: ""},
  {codigo_sp: "QUQB", codigo: "QB", genero_id: 54, nombre_cientifico: "Quercus borealis", nombre_comun: "Roble americano", inscripcion_inase: ""},
  {codigo_sp: "QUQR", codigo: "QR", genero_id: 54, nombre_cientifico: "Quercus robur", nombre_comun: "Roble europeo", inscripcion_inase: ""},
  {codigo_sp: "RORP", codigo: "RP", genero_id: 55, nombre_cientifico: "Robinia pseudoacacia", nombre_comun: "Acacia blanca", inscripcion_inase: ""},
  {codigo_sp: "SANA", codigo: "NA", genero_id: 56, nombre_cientifico: "Salix sp.", nombre_comun: "Sauce", inscripcion_inase: ""},
  {codigo_sp: "SASA", codigo: "SA", genero_id: 56, nombre_cientifico: "Salix alba", nombre_comun: "Sauce blanco", inscripcion_inase: ""},
  {codigo_sp: "SASA01", codigo: "SA", genero_id: 56, nombre_cientifico: "Salix babylonica x Salix alba cv \"131-25\"", nombre_comun: "Sauce 131-25", inscripcion_inase: "Trámite RNC"},
  {codigo_sp: "SASA02", codigo: "SA", genero_id: 56, nombre_cientifico: "Salix babylonica x Salix alba cv ¨131-27¨", nombre_comun: "Sauce 131-27", inscripcion_inase: "Trámite RNC"},
  {codigo_sp: "SASASC", codigo: "SA", genero_id: 56, nombre_cientifico: "Salix alba var. calva", nombre_comun: "Sauce álamo", inscripcion_inase: ""},
  {codigo_sp: "SASB", codigo: "SB", genero_id: 56, nombre_cientifico: "Salix babylonica", nombre_comun: "Sauce llorón", inscripcion_inase: ""},
  {codigo_sp: "SASC", codigo: "SC", genero_id: 56, nombre_cientifico: "Salix babylonica var. sacramenta", nombre_comun: "Sauce americano", inscripcion_inase: "Trámite RNC"},
  {codigo_sp: "SASH", codigo: "SH", genero_id: 56, nombre_cientifico: "Salix hibrido", nombre_comun: "Sauce híbrido", inscripcion_inase: ""},
  {codigo_sp: "SASMS1", codigo: "SM", genero_id: 56, nombre_cientifico: "Salix matsudana x Salix alba cv ¨13-44¨", nombre_comun: "Sauce 13-44", inscripcion_inase: "Trámite RNC"},
  {codigo_sp: "SASN", codigo: "SN", genero_id: 56, nombre_cientifico: "Salix nigra", nombre_comun: "Sauce negro", inscripcion_inase: ""},
  {codigo_sp: "SASN04", codigo: "SN", genero_id: 56, nombre_cientifico: "Salix nigra 4", nombre_comun: "Salix nigra 4", inscripcion_inase: "Trámite RNC"},
  {codigo_sp: "STSJ", codigo: "SJ", genero_id: 58, nombre_cientifico: "Styphnolobyum japonicum", nombre_comun: "Sófora", inscripcion_inase: ""},
  {codigo_sp: "SWSM", codigo: "SM", genero_id: 59, nombre_cientifico: "Swietenia macrophylla", nombre_comun: "Caoba", inscripcion_inase: ""},
  {codigo_sp: "TATD", codigo: "TD", genero_id: 60, nombre_cientifico: "Taxodium distichum", nombre_comun: "Ciprés calvo o ciprés de los pantanos", inscripcion_inase: ""},
  {codigo_sp: "TBNA", codigo: "NA", genero_id: 61, nombre_cientifico: "Tabebuia sp.", nombre_comun: "", inscripcion_inase: ""},
  {codigo_sp: "TBTA", codigo: "TA", genero_id: 61, nombre_cientifico: "Tabebuia avellanedae", nombre_comun: "Lapacho rosado", inscripcion_inase: ""},
  {codigo_sp: "TBTI", codigo: "TI", genero_id: 61, nombre_cientifico: "Tabebuia ipe", nombre_comun: "Lapacho negro", inscripcion_inase: ""},
  {codigo_sp: "TETG", codigo: "TG", genero_id: 62, nombre_cientifico: "Tectona grandis", nombre_comun: "Teca", inscripcion_inase: ""},
  {codigo_sp: "TITC", codigo: "TC", genero_id: 63, nombre_cientifico: "Tilia cordata", nombre_comun: "Tilo", inscripcion_inase: ""},
  {codigo_sp: "TOTC", codigo: "TC", genero_id: 65, nombre_cientifico: "Toona ciliata", nombre_comun: "Toona", inscripcion_inase: "MB"},
  {codigo_sp: "TPTT", codigo: "TT", genero_id: 66, nombre_cientifico: "Tipuana tipu", nombre_comun: "Tipa blanca", inscripcion_inase: ""},
  {codigo_sp: "ULUP", codigo: "UP", genero_id: 67, nombre_cientifico: "Ulmus procera", nombre_comun: "Olmo europeo", inscripcion_inase: ""},
  {codigo_sp: "ULUU", codigo: "UU", genero_id: 67, nombre_cientifico: "Ulmus pumila", nombre_comun: "Olmo siberiano", inscripcion_inase: ""},
  {codigo_sp: "VAEX", codigo: "EX", genero_id: 68, nombre_cientifico: "Sp. Exóticas", nombre_comun: "Mixto", inscripcion_inase: ""},
  {codigo_sp: "VANA", codigo: "NA", genero_id: 68, nombre_cientifico: "Sp. Varias", nombre_comun: "Mixto", inscripcion_inase: ""},
  {codigo_sp: "VANT", codigo: "NT", genero_id: 68, nombre_cientifico: "Sp. Nativas", nombre_comun: "Mixto", inscripcion_inase: ""},
  {codigo_sp: "MRNA", codigo: "NA", genero_id: 38, nombre_cientifico: "Myroxylon sp.", nombre_comun: "", inscripcion_inase: ""},
  {codigo_sp: "QUNA", codigo: "NA", genero_id: 54, nombre_cientifico: "Quercus sp.", nombre_comun: "Roble", inscripcion_inase: ""},
  {codigo_sp: "ARAR", codigo: "AR", genero_id: 7, nombre_cientifico: "Araucaria araucana", nombre_comun: "Pehuén", inscripcion_inase: ""},
  {codigo_sp: "TONA", codigo: "NA", genero_id: 65, nombre_cientifico: "Toona sp.", nombre_comun: "", inscripcion_inase: ""},
  {codigo_sp: "APAQ", codigo: "AQ", genero_id: 6, nombre_cientifico: "Aspidosperma quebracho-blanco", nombre_comun: "Quebracho Blanco", inscripcion_inase: ""},
  {codigo_sp: "ASAB", codigo: "AB", genero_id: 8, nombre_cientifico: "Astronium balansae", nombre_comun: "Urunday", inscripcion_inase: ""},
  {codigo_sp: "ASAU", codigo: "AU", genero_id: 8, nombre_cientifico: "Astronium urundeuva", nombre_comun: "Urundel", inscripcion_inase: ""},
  {codigo_sp: "ATAA", codigo: "AA", genero_id: 9, nombre_cientifico: "Artemisia annua", nombre_comun: "", inscripcion_inase: ""},
  {codigo_sp: "CRCC", codigo: "CC", genero_id: 19, nombre_cientifico: "Corymbia citriodora", nombre_comun: "", inscripcion_inase: ""},
  {codigo_sp: "CRCM", codigo: "CM", genero_id: 19, nombre_cientifico: "Corymbia maculata", nombre_comun: "", inscripcion_inase: ""},
  {codigo_sp: "CRCV", codigo: "CV", genero_id: 19, nombre_cientifico: "Corymbia variegata", nombre_comun: "", inscripcion_inase: ""},
  {codigo_sp: "CUCA", codigo: "CA", genero_id: 21, nombre_cientifico: "Cupressus arizonica", nombre_comun: "Ciprés de Arizona", inscripcion_inase: ""},
  {codigo_sp: "CUNA", codigo: "NA", genero_id: 21, nombre_cientifico: "Cupressus sp.", nombre_comun: "Ciprés", inscripcion_inase: ""},
  {codigo_sp: "EUEB", codigo: "EB", genero_id: 24, nombre_cientifico: "Eucalyptus badjensis", nombre_comun: "Eucalipto badjensis", inscripcion_inase: ""},
  {codigo_sp: "EUEN", codigo: "EN", genero_id: 24, nombre_cientifico: "Eucalyptus nitens", nombre_comun: "Eucalipto brillante", inscripcion_inase: ""},
  {codigo_sp: "EUER", codigo: "ER", genero_id: 24, nombre_cientifico: "Eucalyptus urograndis", nombre_comun: "", inscripcion_inase: ""},
  {codigo_sp: "EUNANA", codigo: "NA", genero_id: 24, nombre_cientifico: "Eucalyptus sp. cl.", nombre_comun: "Eucalipto clon", inscripcion_inase: ""},
  {codigo_sp: "GLGA", codigo: "GA", genero_id: 26, nombre_cientifico: "Gleditsia amorphoides", nombre_comun: "Espina corona", inscripcion_inase: ""},
  {codigo_sp: "JAJM", codigo: "JM", genero_id: 29, nombre_cientifico: "Jacaranda mimosifolia", nombre_comun: "Tarco", inscripcion_inase: ""},
  {codigo_sp: "JUJA", codigo: "JA", genero_id: 30, nombre_cientifico: "Juglans australis", nombre_comun: "Nogal Criollo", inscripcion_inase: ""},
  {codigo_sp: "NONB", codigo: "NB", genero_id: 40, nombre_cientifico: "Nothofagus betuloides", nombre_comun: "Guindo", inscripcion_inase: ""},
  {codigo_sp: "NOND", codigo: "ND", genero_id: 40, nombre_cientifico: "Nothofagus dombeyi", nombre_comun: "Coihue", inscripcion_inase: ""},
  {codigo_sp: "PANA", codigo: "NA", genero_id: 41, nombre_cientifico: "Paulownia sp.", nombre_comun: "", inscripcion_inase: ""},
  {codigo_sp: "PCPP", codigo: "PP", genero_id: 42, nombre_cientifico: "Podocarpus parlatorei", nombre_comun: "Pino del Cerro", inscripcion_inase: ""},
  {codigo_sp: "PGPN", codigo: "PN", genero_id: 45, nombre_cientifico: "Pterogyne nitens", nombre_comun: "Viraró", inscripcion_inase: ""},
  {codigo_sp: "PHPR", codigo: "PR", genero_id: 46, nombre_cientifico: "Phyllostylon rhamnoides", nombre_comun: "Palo Lanza", inscripcion_inase: ""},
  {codigo_sp: "PIPC01", codigo: "PC", genero_id: 47, nombre_cientifico: "Pinus caribaea var. Hondurensis x elliottii", nombre_comun: "Pinus caribaea var. Hondurensis x elliottii", inscripcion_inase: ""},
  {codigo_sp: "POPAPB", codigo: "PA", genero_id: 49, nombre_cientifico: "Populus alba var. pyramidalis Bunge", nombre_comun: "Chopo boleana, Álamo plateado columnar o piramidal.", inscripcion_inase: ""},
  {codigo_sp: "POPC02", codigo: "PC", genero_id: 49, nombre_cientifico: "Populus x euroamericana cv. \"I-488\"", nombre_comun: "Populus x euroamericana cv. \"I-488\"", inscripcion_inase: ""},
  {codigo_sp: "POPC03", codigo: "PC", genero_id: 49, nombre_cientifico: "Populus x euroamericana cv. \"I-455\"", nombre_comun: "Populus x euroamericana cv. \"I-455\"", inscripcion_inase: ""},
  {codigo_sp: "POPD11", codigo: "PD", genero_id: 49, nombre_cientifico: "Populus deltoides cv. 190/68", nombre_comun: "Populus deltoides cv. 190/68", inscripcion_inase: ""},
  {codigo_sp: "POPD12", codigo: "PD", genero_id: 49, nombre_cientifico: "Populus deltoides cv. 107/68", nombre_comun: "Populus deltoides cv. 107/68", inscripcion_inase: ""},
  {codigo_sp: "POPD13", codigo: "PD", genero_id: 49, nombre_cientifico: "Populus deltoides cv. 125/68", nombre_comun: "Populus deltoides cv. 125/68", inscripcion_inase: ""},
  {codigo_sp: "POPD14", codigo: "PD", genero_id: 49, nombre_cientifico: "Populus deltoides cv. Alton", nombre_comun: "Populus deltoides cv. Alton", inscripcion_inase: ""},
  {codigo_sp: "POPD15", codigo: "PD", genero_id: 49, nombre_cientifico: "Populus deltoides cv. \"Stoneville 109\"", nombre_comun: "Populus deltoides cv. \"Stoneville 109\"", inscripcion_inase: ""},
  {codigo_sp: "POPD16", codigo: "PD", genero_id: 49, nombre_cientifico: "Populus deltoides cv. \"Stoneville 71\"", nombre_comun: "Populus deltoides cv. \"Stoneville 71\"", inscripcion_inase: ""},
  {codigo_sp: "POPD17", codigo: "PD", genero_id: 49, nombre_cientifico: "Populus deltoides cv. \"Stoneville 77\"", nombre_comun: "Populus deltoides cv. \"Stoneville 77\"", inscripcion_inase: ""},
  {codigo_sp: "PPPK", codigo: "PK", genero_id: 50, nombre_cientifico: "Prosopis kuntzei", nombre_comun: "Itín", inscripcion_inase: ""},
  {codigo_sp: "QUQS", codigo: "QS", genero_id: 54, nombre_cientifico: "Quercus Sessiliflora", nombre_comun: "Roble blanco americano", inscripcion_inase: ""},
  {codigo_sp: "SASN03", codigo: "SN", genero_id: 56, nombre_cientifico: "Salix nigra 3", nombre_comun: "Salix nigra 3", inscripcion_inase: ""},
  {codigo_sp: "SASR", codigo: "SR", genero_id: 56, nombre_cientifico: "Salix x argentinensis", nombre_comun: "Lazarín", inscripcion_inase: ""},
  {codigo_sp: "SCNA", codigo: "NA", genero_id: 57, nombre_cientifico: "Schinopsis sp.", nombre_comun: "", inscripcion_inase: ""},
  {codigo_sp: "SCSB", codigo: "SB", genero_id: 57, nombre_cientifico: "Schinopsis balansae", nombre_comun: "Quebracho colorado chaqueño", inscripcion_inase: ""},
  {codigo_sp: "SCSQ", codigo: "SQ", genero_id: 57, nombre_cientifico: "Schinopsis quebracho-colorado", nombre_comun: "Quebracho colorado santiagueño", inscripcion_inase: ""},
  {codigo_sp: "SWNA", codigo: "NA", genero_id: 59, nombre_cientifico: "Swietenia sp.", nombre_comun: "", inscripcion_inase: ""},
  {codigo_sp: "TMNA", codigo: "NA", genero_id: 64, nombre_cientifico: "Tamarix sp.", nombre_comun: "", inscripcion_inase: ""},
  {codigo_sp: "ULNA", codigo: "NA", genero_id: 67, nombre_cientifico: "Ulmus sp.", nombre_comun: "", inscripcion_inase: ""},
  {codigo_sp: "PIPX", codigo: "PX", genero_id: 47, nombre_cientifico: "Pinus oocarpa", nombre_comun: "Pino ocote", inscripcion_inase: ""},
  {codigo_sp: "VEVF", codigo: "VF", genero_id: 69, nombre_cientifico: "Vernicia fordii", nombre_comun: "Tung", inscripcion_inase: ""},
  {codigo_sp: "GRNA", codigo: "NA", genero_id: 27, nombre_cientifico: "Grevillea sp.", nombre_comun: "Grevilea", inscripcion_inase: ""},
  {codigo_sp: "TOTCAU", codigo: "TC", genero_id: 65, nombre_cientifico: "Toona ciliata var. australis", nombre_comun: "Toona", inscripcion_inase: ""},
  {codigo_sp: "CRNA", codigo: "NA", genero_id: 19, nombre_cientifico: "Corymbia sp.", nombre_comun: "", inscripcion_inase: ""},
  {codigo_sp: "POPF02", codigo: "PF", genero_id: 49, nombre_cientifico: "Populus x canadensis cv. 568/1", nombre_comun: "Populus x canadensis cv. 568/1", inscripcion_inase: ""},
  {codigo_sp: "HONA", codigo: "NA", genero_id: 28, nombre_cientifico: "Hovenia sp.", nombre_comun: "Hovenia", inscripcion_inase: ""},
  {codigo_sp: "POPH", codigo: "PH", genero_id: 49, nombre_cientifico: "Populus nigra cv \"Thayssiana\"", nombre_comun: "Álamo chileno", inscripcion_inase: ""},
  {codigo_sp: "POPS", codigo: "PS", genero_id: 49, nombre_cientifico: "Populus simonii", nombre_comun: "Álamo chino", inscripcion_inase: ""}
])
