Responsable.create!([
  {codigo: "1", iniciales: "CH", nombre: "Carola Hermelo", activo: false},
  {codigo: "2", iniciales: "AAB", nombre: "Ariel Boromeo", activo: false},
  {codigo: "3", iniciales: "ACP", nombre: "Ana Clara Pla", activo: true},
  {codigo: "4", iniciales: "JP", nombre: "Juan Poch", activo: true},
  {codigo: "5", iniciales: "SF", nombre: "Sebastián Fernandez", activo: false},
  {codigo: "6", iniciales: "GZ", nombre: "Gabriel Zalazar", activo: false},
  {codigo: "7", iniciales: "MG", nombre: "Matias Gaute", activo: true},
  {codigo: "8", iniciales: "PR", nombre: "Paola Riguetti", activo: false},
  {codigo: "9", iniciales: "LF", nombre: "Lorena Flores", activo: false},
  {codigo: "10", iniciales: "DDD", nombre: "Diego Dominguez Daguer", activo: false},
  {codigo: "11", iniciales: "RB", nombre: "Roberto Benitez", activo: true},
  {codigo: "12", iniciales: "MY", nombre: "Marcelo Yorio", activo: true},
  {codigo: "13", iniciales: "FML", nombre: "Francisco Laxague", activo: true},
  {codigo: "14", iniciales: "NC", nombre: "Nora Clemente", activo: true},
  {codigo: "15", iniciales: "FSP", nombre: "Fernanda Pietrantuono", activo: true},
  {codigo: "16", iniciales: "Sin Especi", nombre: "Sin Especificar", activo: false},
  {codigo: "17", iniciales: "Otros", nombre: "Otros", activo: false},
  {codigo: "18", iniciales: "IB", nombre: "Inti Bonomo", activo: true},
  {codigo: "19", iniciales: "AS", nombre: "Ana Saura", activo: true},
  {codigo: "23", iniciales: "FA", nombre: "Federico Alonso", activo: false},
  {codigo: "24", iniciales: "EGS", nombre: "Esteban Gabriel Spinetto", activo: true},
  {codigo: "25", iniciales: "AD", nombre: "Agustín Demarco", activo: true},
  {codigo: "26", iniciales: "NT", nombre: "Nahuel Tripodi", activo: true},
  {codigo: "27", iniciales: "GS", nombre: "Gonzalo Sciortino", activo: true},
  {codigo: "28", iniciales: "FH", nombre: "Fernando Horn", activo: true},
  {codigo: "29", iniciales: "CDT", nombre: "Candela De Titto", activo: true},
  {codigo: "30", iniciales: "ER", nombre: "Pedro Rivolta", activo: true},
  {codigo: "31", iniciales: "MC", nombre: "Mercedes Ciccale", activo: true},
  {codigo: "32", iniciales: "LBA", nombre: "Lucía Alfonzo", activo: true},
  {codigo: "33", iniciales: "SP", nombre: "Sol Peirano", activo: true},
  {codigo: "34", iniciales: "OEB", nombre: "Oscar Emanuel Barreto", activo: false},
  {codigo: "35", iniciales: "SB", nombre: "Sebastian Ignacio  Besteiro", activo: false},
  {codigo: "36", iniciales: "AJT", nombre: "Adolfo Javier Torres", activo: false},
  {codigo: "37", iniciales: "FV", nombre: "Flavia Romina Vázquez", activo: false},
  {codigo: "38", iniciales: "STL", nombre: "Santiago Liebana", activo: false},
  {codigo: "39", iniciales: "LG", nombre: "Leandro Granieri", activo: false},
  {codigo: "40", iniciales: "GP", nombre: "Guido Petrazzini", activo: false},
  {codigo: "41", iniciales: "CD", nombre: "Cristina Dellacanonica", activo: false},
  {codigo: "42", iniciales: "IC", nombre: "Ivana Collamarino", activo: false},
  {codigo: "43", iniciales: "IF", nombre: "Ileana Frasier", activo: false},
  {codigo: "44", iniciales: "NP", nombre: "Nelson Ponce", activo: false},
  {codigo: "45", iniciales: "PJH", nombre: "Pablo Horak", activo: false},
  {codigo: "46", iniciales: "AG", nombre: "Agustin Gowland", activo: false},
  {codigo: "47", iniciales: "CN", nombre: "Carlos Nervo", activo: false},
  {codigo: "48", iniciales: "FDS", nombre: "Fernando Salvare", activo: false},
  {codigo: "49", iniciales: "EGV", nombre: "Eduardo Gonzalez Vidal", activo: false},
  {codigo: "50", iniciales: "OB", nombre: "Eduardo Basile", activo: false},
  {codigo: "51", iniciales: "MCL", nombre: "Martin Lopez", activo: false},
  {codigo: "52", iniciales: "MDA", nombre: "Marina D´angelo", activo: false},
  {codigo: "53", iniciales: "MF", nombre: "Marcelo Falconier", activo: false},
  {codigo: "54", iniciales: "AI", nombre: "Ariana Iaconis", activo: false},
  {codigo: "55", iniciales: "NDT", nombre: "Niciolas Del Tufo", activo: false},
  {codigo: "56", iniciales: "JFM", nombre: "Julio Mondini", activo: false},
  {codigo: "57", iniciales: "LIF", nombre: "Laura Faustino", activo: false},
  {codigo: "58", iniciales: "JPB", nombre: "Juan Pablo Bruno", activo: false},
  {codigo: "59", iniciales: "JM", nombre: "Juan Marcovecchio", activo: false},
  {codigo: "60", iniciales: "ME", nombre: "Eugenia Escoda", activo: false},
  {codigo: "61", iniciales: "EJDM", nombre: "Ezequiel Di Marco", activo: false},
  {codigo: "62", iniciales: "CW", nombre: "Carolina Williams", activo: false},
  {codigo: "63", iniciales: "CLL", nombre: "Carolina Llavallol", activo: false},
  {codigo: "64", iniciales: "DG", nombre: "Daniela Garcia", activo: false},
  {codigo: "65", iniciales: "FA", nombre: "Franco Armento", activo: false},
  {codigo: "66", iniciales: "NG", nombre: "Nicolas Graffia", activo: false},
  {codigo: "67", iniciales: "MCR", nombre: "Milagros Castro Rios", activo: false}
])
