require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TecnicosController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Tecnico. As you add validations to Tecnico, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TecnicosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all tecnicoses as @tecnicoses" do
      tecnico = Tecnico.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:tecnicos)).to eq([tecnico])
    end
  end

  describe "GET show" do
    it "assigns the requested tecnico as @tecnico" do
      tecnico = Tecnico.create! valid_attributes
      get :show, {:id => tecnico.to_param}, valid_session
      expect(assigns(:tecnico)).to eq(tecnico)
    end
  end

  describe "GET new" do
    it "assigns a new tecnico as @tecnico" do
      get :new, {}, valid_session
      expect(assigns(:tecnico)).to be_a_new(Tecnico)
    end
  end

  describe "GET edit" do
    it "assigns the requested tecnico as @tecnico" do
      tecnico = Tecnico.create! valid_attributes
      get :edit, {:id => tecnico.to_param}, valid_session
      expect(assigns(:tecnico)).to eq(tecnico)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tecnico" do
        expect {
          post :create, {:tecnico => valid_attributes}, valid_session
        }.to change(Tecnico, :count).by(1)
      end

      it "assigns a newly created tecnico as @tecnico" do
        post :create, {:tecnico => valid_attributes}, valid_session
        expect(assigns(:tecnico)).to be_a(Tecnico)
        expect(assigns(:tecnico)).to be_persisted
      end

      it "redirects to the created tecnico" do
        post :create, {:tecnico => valid_attributes}, valid_session
        expect(response).to redirect_to(Tecnico.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tecnico as @tecnico" do
        post :create, {:tecnico => invalid_attributes}, valid_session
        expect(assigns(:tecnico)).to be_a_new(Tecnico)
      end

      it "re-renders the 'new' template" do
        post :create, {:tecnico => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tecnico" do
        tecnico = Tecnico.create! valid_attributes
        put :update, {:id => tecnico.to_param, :tecnico => new_attributes}, valid_session
        tecnico.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested tecnico as @tecnico" do
        tecnico = Tecnico.create! valid_attributes
        put :update, {:id => tecnico.to_param, :tecnico => valid_attributes}, valid_session
        expect(assigns(:tecnico)).to eq(tecnico)
      end

      it "redirects to the tecnico" do
        tecnico = Tecnico.create! valid_attributes
        put :update, {:id => tecnico.to_param, :tecnico => valid_attributes}, valid_session
        expect(response).to redirect_to(tecnico)
      end
    end

    describe "with invalid params" do
      it "assigns the tecnico as @tecnico" do
        tecnico = Tecnico.create! valid_attributes
        put :update, {:id => tecnico.to_param, :tecnico => invalid_attributes}, valid_session
        expect(assigns(:tecnico)).to eq(tecnico)
      end

      it "re-renders the 'edit' template" do
        tecnico = Tecnico.create! valid_attributes
        put :update, {:id => tecnico.to_param, :tecnico => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tecnico" do
      tecnico = Tecnico.create! valid_attributes
      expect {
        delete :destroy, {:id => tecnico.to_param}, valid_session
      }.to change(Tecnico, :count).by(-1)
    end

    it "redirects to the tecnicos list" do
      tecnico = Tecnico.create! valid_attributes
      delete :destroy, {:id => tecnico.to_param}, valid_session
      expect(response).to redirect_to(tecnicos_url)
    end
  end

end
